### ISSUE TITLE
from boxx import Markdown 

### ISSUE THREAD

**Issue by hu5tao** [DIYer22/retail_product_checkout_tools#2]
ImportError: cannot import name 'Markdown'?thank you, how to solve it?

**Comment by DIYer22** [comment]
I try `from boxx import Markdown` in a new Python enviroment, and don't get any error.  Could you please provide more infomation, like Exception trace?

**Comment by hu5tao** [comment]
And i find that the reason that boxx version  boxx-0.9.2.17 can solve it. or pip install rpctool direct ly.
