### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by RDSJC** [DIYer22/retail_product_checkout_tools#3]
![bug2](https://user-images.githubusercontent.com/8330000/106360001-1de54e80-6351-11eb-831f-cafc5da45ee7.png)
When I ran the test command, an error happened as shown.  One of the empty array lead to the error but I really don't know how it happened. I really hope you can help me, thanks!

**Comment by DIYer22** [comment]
I am not sure what is happening, maybe your result json is empty.
