### ISSUE TITLE
__raw_Chinese_name_df 中name : "4e0a597d4f73837751708c4655g"，怎么翻译成中文名称

### ISSUE THREAD

**Issue by xinsuinizhuan** [DIYer22/retail_product_checkout_tools#5]
![图片](https://user-images.githubusercontent.com/40679769/130390060-2ba0e599-8101-4951-9a50-05987ac5810e.png)

**Comment by DIYer22** [comment]
![image](https://user-images.githubusercontent.com/10448025/130390215-5d5bb3b6-b48c-4f12-93e6-2a7ac321a244.png)


可能是你用的解析软件的编码不支持中文吧, 要用 utf-8 编码
